import type { Client } from '@/models/UserResponse';
import type { Bid } from '@/models/BidResponse';

export const makeClient = (overrides: Partial<Client> = {}): Client => ({
  id: 1,
  full_name: 'Test Client',
  phone: '+10000000000',
  telegram: '@test',
  company: null,
  address: null,
  email: 'test@example.com',
  ...overrides,
});

export const makeBid = (overrides: Partial<Bid> = {}): Bid => ({
  id: 1,
  client: makeClient(),
  brand: 'Toyota',
  model: 'Camry',
  vin: 'VIN123456789012345',
  v_type: { id: 1, v_type: 'car' },
  price: 25000,
  container_number: 'CONT123456',
  arrival_date: '2024-01-15',
  transporter: 'Test Transporter',
  recipient: 'Test Recipient',
  transit_method: null,
  acceptance_type: null,
  location: null,
  requested_title: false,
  notified_parking: false,
  notified_inspector: false,
  openning_date: null,
  approved_by_inspector: false,
  approved_by_title: false,
  approved_by_re_export: false,
  opened: false,
  manager_comment: null,
  pickup_address: null,
  title_collection_date: null,
  took_title: null,
  notified_logistician_by_inspector: false,
  acceptance_date: null,
  transit_number: null,
  inspection_done: null,
  inspection_date: null,
  number_sent: false,
  number_sent_date: null,
  inspection_paid: false,
  inspector_comment: null,
  export: false,
  prepared_documents: false,
  vehicle_transporter: {
    id: 1,
    number: 'АВ-123-45',
  },
  logistician_keys_number: 1,
  vehicle_arrival_date: null,
  receive_vehicle: false,
  receive_documents: false,
  full_acceptance: false,
  receiver_keys_number: 1,
  ...overrides,
});
